#!/usr/bin/env python3
"""Step 2: generate Splunk searches from the log signatures.

For every signature: a search on its anchor text plus a rex that extracts the same named fields. For every flow: one
combined search that pulls all of the flow's lines and groups them by correlation id, so the analyst can eyeball
traces in Splunk before exporting.

Usage: spl_from_signatures.py signatures.json --index osb --sourcetype weblogic_stdout -o queries.spl
The index and sourcetype are environment-specific: ask the Splunk owner (they are usually not 'main').
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path


def pcre(py_regex: str) -> str:
    """Python named groups -> PCRE named groups; escape characters that end an SPL string."""
    return py_regex.replace("(?P<", "(?<").replace("\\", "\\\\").replace('"', '\\"')


def spl_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("signatures", type=Path)
    ap.add_argument("--index", required=True)
    ap.add_argument("--sourcetype", required=True)
    ap.add_argument("-o", "--out", type=Path, default=Path("queries.spl"))
    args = ap.parse_args()
    sigs = [s for s in json.loads(args.signatures.read_text(encoding="utf-8"))["signatures"] if s.get("regex")]
    base = f'index={args.index} sourcetype="{args.sourcetype}"'
    lines = ["``` Generated by spl_from_signatures.py. Run with an explicit time range that covers a full business cycle. ```", ""]
    by_flow = defaultdict(list)
    for s in sigs:
        by_flow[s["flow"]].append(s)
        lines += [f"``` {s['id']}  stage={s['stage']}  pipeline={s['pipeline_type']}  level={s['level']} ```",
                  f'{base} "{spl_string(s["anchor"])}"',
                  f'| rex field=_raw max_match=1 "(?s){pcre(s["regex"])}"',
                  "| table _time " + " ".join(g["name"] for g in s["groups"] if g["name"] != "body") + " _raw", ""]
    for flow, ss in by_flow.items():
        anchors = " OR ".join(f'"{spl_string(s["anchor"])}"' for s in ss)
        corr = sorted({c for s in ss for c in s["roles"]["correlation"]})
        rexes = "\n".join(f'| rex field=_raw max_match=1 "(?s){pcre(s["regex"])}"' for s in ss)
        lines += [f"``` EXPORT for {flow}: run this one, then Export -> CSV. Keeps one row per log line (_time, _raw). ```",
                  f"{base} ({anchors})",
                  "| sort 0 _time",
                  "| table _time _raw", ""]
        lines += [f"``` TRACES for {flow}: all lines grouped by correlation id (to look at, not to export) ```",
                  f"{base} ({anchors})", rexes,
                  f"| eval corr=coalesce({', '.join(corr)})" if corr else "| eval corr=\"NO-CORRELATION-FIELD\"",
                  "| stats min(_time) as start max(_time) as end count as lines values(source) as sources list(_raw) as events by corr",
                  "| sort - start", ""]
    lines += ["``` Export (REST, JSON lines), e.g.:",
              "curl -sk -H \"Authorization: Bearer $SPLUNK_TOKEN\" https://<splunk>:8089/services/search/jobs/export \\",
              "  --data-urlencode search='search <one of the searches above>' -d earliest_time=-30d -d latest_time=now -d output_mode=json > events.jsonl",
              "or: SPLUNK_TOKEN=... python3 tools/splunk_export.py --url https://<splunk>:8089 --search '<the EXPORT search>' --earliest -30d -o events.jsonl ```"]
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(sigs)} signature searches and {len(by_flow)} trace searches -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
